<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Full width slider generated by WOWSlider.com</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Full width slider" />
    <!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
    <link rel="stylesheet" type="text/css" href="engine1/style.css" />
    <script type="text/javascript" src="engine1/jquery.js"></script>

    <meta charset="UTF-8">
    <title>getElementsByTagName</title>
    <link type="text/css" href="menu.css" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="bootstrap.css">  
    <style type="text/css">
        * { margin:0;
        padding:0;
        }
        body { background: url(); }
        #menu { margin-top:-1.5%; }
    </style>
</head>
<body style="background-color:;margin:auto">
    <!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
    <div id="wowslider-container1">
    <div class="ws_images"><ul>
<li><img src="data1/images/bg_uno.jpg" alt="Minitecoloco busca,evalua y presenta candidatos" title="Minitecoloco busca,evalua y presenta candidatos" id="wows1_0"/></li>
<li><img src="data1/images/bg_cuatro.jpg" alt="Elimina la distancia geográfica entre los candidatos y los grupos de interés" title="Elimina la distancia geográfica entre los candidatos y los grupos de interés" id="wows1_1"/></li>
<li><a href="http://wowslider.com/vf"><img src="data1/images/bg_dos.jpg" alt="full screen slider" title="Minitecoloco es la sociedad cotizada multinacional basada en la tecnología" id="wows1_2"/></a></li>
<li><img src="data1/images/bg_tres.jpg" alt="Tecnología diseñada para llevar acabo las mejores decisiones" title="Tecnología diseñada para llevar acabo las mejores decisiones" id="wows1_3"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="Minitecoloco busca,evalua y presenta candidatos"><img src="data1/tooltips/bg_uno.jpg" alt="Minitecoloco busca,evalua y presenta candidatos"/></a>
<a href="#" title="Elimina la distancia geográfica entre los candidatos y los grupos de interés"><img src="data1/tooltips/bg_cuatro.jpg" alt="Elimina la distancia geográfica entre los candidatos y los grupos de interés"/></a>
<a href="#" title="Minitecoloco es la sociedad cotizada multinacional basada en la tecnología"><img src="data1/tooltips/bg_dos.jpg" alt="Minitecoloco es la sociedad cotizada multinacional basada en la tecnología"/></a>
<a href="#" title="Tecnología diseñada para llevar acabo las mejores decisiones"><img src="data1/tooltips/bg_tres.jpg" alt="Tecnología diseñada para llevar acabo las mejores decisiones"/></a>
</div></div><span class="wsl"><a href="http://wowslider.com/vf">full width slider</a> by WOWSlider.com v6.6</span>
    <div class="ws_shadow"></div>
    </div>  
    <script type="text/javascript" src="engine1/wowslider.js"></script>
    <script type="text/javascript" src="engine1/script.js"></script>
    <!-- End WOWSlider.com BODY section -->
<div id="menu">
    <ul class="menu" style="z-index:100">
        <li><a href="#" class="parent"><span>Inicio</span></a>
        <li><a href="#" class="parent"><span>Empleos</span></a>
            <div class="columns two">
                <ul class="one">
                    <li><a href="#"><span>Sub Item 1.1</span></a></li>
                    <li><a href="#"><span>Sub Item 1.2</span></a></li>
            </div>
        </li>
        <li><a href="#" class="unique"><span>Empresas</span></a></li>
        <li class="last"><a href="#"  class="unique"><span>Profesionales</span></a></li>
        <li class="last"><a href="#"  class="unique"><span>Ayuda</span></a></li>
                <li class="last"><a href="#"  class="unique"><span>Contactanos</span></a></li>
    </ul>
</div>

<div>

</form>
                                 

<div class="container">
    <div class="contenido"> 
        <div class="jumbotron navbar-collapse collapse">
    <div class="arrow-left hidden-xs hidden-sm"></div>
    <div class="arrow-right hidden-xs hidden-sm"></div>
    <div class="container">
        <div class="row">

            <form id="frmBuscador" method="post" action="/set-filter-params" data-tipo-actual="empleo" data-tipo-busqueda="/emprego" data-all-groups="no">
                <div class="col-md-3">
                    <div class="row">

                        <label>Buscar por</label>
                        <select name="tipoBusqueda" id="tipoBusqueda">
          <option value="Empleos">Empleos</option>
          <option value="Profesionales">Profesionales</option>
          <option value="Empresas">Empresas</option>
        </select>

                                          </div>
                </div>
                <div class="col-md-7">
                    <input type="hidden" id="frmBuscador-filter-params" value="" />                        
                    <input type="text" name="cadena" id="frmBuscadorCadena" value=""  placeholder="Escriba aqui texto" class="form-control">
                </div>
                                <div class="col-md-2"><button class="col-md-12 btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"></span> BUSCAR</button></div>
            </form>

<br>
<br>
            <div class="row">
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>

            <h2 class="text-center h2-home"><strong>Todas las oportunidades profesionales están en Red Trabajar</strong></h2>
            <h2 class="text-center h2-home text-muted" >14,695 profesionales y 49 empleos te esperan</h2>

            <br>
            <br>
            <div class="col-md-3 home-images text-center">
                <img src="images/chica-rubia.jpg" alt="Progra4" title="Progra4" class="img-circle" />                <p class="comments-home text-primary">Ha encontrado su nuevo empleo</p>
            </div>
            <div class="col-md-3 home-images text-center">
                <img src="images/chico-joven.jpg" alt="Progra4" title="Progra4" class="img-circle"/>                <p class="comments-home text-success">Destaca en su campo profesional</p>
            </div>
            <div class="col-md-3 home-images text-center">
                <img src="images/chica-morena.jpg" alt="Progra4" title="Progra4" class="img-circle"/>                <p class="comments-home text-warning">Recibió presupuestos gratis</p>
            </div>
            <div class="col-md-3 home-images text-center">
                <img src="images/chico-traje.jpg" alt="Progra4" title="Progra4" class="img-circle"/>                <p class="comments-home text-danger">Consiguió nuevos clientes</p>
            </div>

            <div class="col-md-offset-3 col-md-6 text-center logins">
                <br>
                <br>
                <a href="registrate.php" class="btn btn-lg btn-primary btn-home btn btn-primary btn-lg btn-block"><strong>Únete ahora como usuario, ¡es gratis!</strong></a>
                <a href=".php" class="on-login">Si ya tienes cuenta, inicia sesión</a>

               <br>
               <br>
                <a href="" class="btn btn-lg btn-primary btn-home btn btn-primary btn-lg btn-block"><strong>Únete ahora como empresa, ¡es gratis!</strong></a>
                <a href=".php" class="on-login">Si ya tienes cuenta, inicia sesión</a>
            </div>
</div>        


 
        </script>
</body>

</html>

