<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Full width slider generated by WOWSlider.com</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="description" content="Made with WOW Slider - Create beautiful, responsive image sliders in a few clicks. Awesome skins and animations. Full width slider" />
    <!-- Start WOWSlider.com HEAD section --> <!-- add to the <head> of your page -->
    <link rel="stylesheet" type="text/css" href="engine1/style.css" />
    <script type="text/javascript" src="engine1/jquery.js"></script>

    <meta charset="UTF-8">
    <title>getElementsByTagName</title>
    <link type="text/css" href="menu.css" rel="stylesheet" /> 
    <link rel="stylesheet" type="text/css" href="bootstrap.css">  
    <style type="text/css">
        * { margin:0;
        padding:0;
        }
        body { background: url(); }
        #menu { margin-top:-1.5%; }
    </style>
</head>
<body style="background-color:;margin:auto">
    <!-- Start WOWSlider.com BODY section --> <!-- add to the <body> of your page -->
    <div id="wowslider-container1">
    <div class="ws_images"><ul>
<li><img src="data1/images/bg_uno.jpg" alt="Minitecoloco busca,evalua y presenta candidatos" title="Minitecoloco busca,evalua y presenta candidatos" id="wows1_0"/></li>
<li><img src="data1/images/bg_cuatro.jpg" alt="Elimina la distancia geográfica entre los candidatos y los grupos de interés" title="Elimina la distancia geográfica entre los candidatos y los grupos de interés" id="wows1_1"/></li>
<li><a href="http://wowslider.com/vf"><img src="data1/images/bg_dos.jpg" alt="full screen slider" title="Minitecoloco es la sociedad cotizada multinacional basada en la tecnología" id="wows1_2"/></a></li>
<li><img src="data1/images/bg_tres.jpg" alt="Tecnología diseñada para llevar acabo las mejores decisiones" title="Tecnología diseñada para llevar acabo las mejores decisiones" id="wows1_3"/></li>
</ul></div>
<div class="ws_bullets"><div>
<a href="#" title="Minitecoloco busca,evalua y presenta candidatos"><img src="data1/tooltips/bg_uno.jpg" alt="Minitecoloco busca,evalua y presenta candidatos"/></a>
<a href="#" title="Elimina la distancia geográfica entre los candidatos y los grupos de interés"><img src="data1/tooltips/bg_cuatro.jpg" alt="Elimina la distancia geográfica entre los candidatos y los grupos de interés"/></a>
<a href="#" title="Minitecoloco es la sociedad cotizada multinacional basada en la tecnología"><img src="data1/tooltips/bg_dos.jpg" alt="Minitecoloco es la sociedad cotizada multinacional basada en la tecnología"/></a>
<a href="#" title="Tecnología diseñada para llevar acabo las mejores decisiones"><img src="data1/tooltips/bg_tres.jpg" alt="Tecnología diseñada para llevar acabo las mejores decisiones"/></a>
</div></div><span class="wsl"><a href="http://wowslider.com/vf">full width slider</a> by WOWSlider.com v6.6</span>
    <div class="ws_shadow"></div>
    </div>  
    <script type="text/javascript" src="engine1/wowslider.js"></script>
    <script type="text/javascript" src="engine1/script.js"></script>
    <!-- End WOWSlider.com BODY section -->
<div id="menu">
    <ul class="menu" style="z-index:100">
        <li><a href="index.php" class="parent"><span>Inicio</span></a>
        <li><a href="#" class="parent"><span>Empleos</span></a>
            <div class="columns two">
                <ul class="one">
                    <li><a href="#"><span>Sub Item 1.1</span></a></li>
                    <li><a href="#"><span>Sub Item 1.2</span></a></li>
            </div>
        </li>
        <li><a href="#" class="unique"><span>Empresas</span></a></li>
        <li class="last"><a href="#"  class="unique"><span>Profesionales</span></a></li>
        <li class="last"><a href="#"  class="unique"><span>Ayuda</span></a></li>
                <li class="last"><a href="#"  class="unique"><span>Contactanos</span></a></li>
    </ul>
</div>

<div>

</form>
                                 

<div class="container">
    <div class="contenido"> 
        <div class="jumbotron navbar-collapse collapse">
    <div class="arrow-left hidden-xs hidden-sm"></div>
    <div class="arrow-right hidden-xs hidden-sm"></div>
    <div class="container">
        <div class="row">

            <form id="frmBuscador" method="post" action="/set-filter-params" data-tipo-actual="empleo" data-tipo-busqueda="/emprego" data-all-groups="no">
                <div class="col-md-3">
                    <div class="row">

                        <label>Buscar por</label>
                        <select name="tipoBusqueda" id="tipoBusqueda">
          <option value="Empleos">Empleos</option>
          <option value="Profesionales">Profesionales</option>
          <option value="Empresas">Empresas</option>
        </select>

                                          </div>
                </div>
                <div class="col-md-7">
                    <input type="hidden" id="frmBuscador-filter-params" value="" />                        
                    <input type="text" name="cadena" id="frmBuscadorCadena" value=""  placeholder="Escriba aqui texto" class="form-control">
                </div>
                                <div class="col-md-2"><button class="col-md-12 btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"></span> BUSCAR</button></div>
            </form>

            <br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


            <form id="frmBuscador" method="post" action="/set-filter-params" data-tipo-actual="empleo" data-tipo-busqueda="/emprego" data-all-groups="no">
                <div class="col-md-3">
                    <div class="row">

                        <label>Buscar por</label>
                        <select name="tipoBusqueda" id="tipoBusqueda">
          <option value="Empleos">Empleos</option>
          <option value="Profesionales">Profesionales</option>
          <option value="Empresas">Empresas</option>
        </select>

                                          </div>
                </div>     
                <div class="col-md-7">
                    <input type="hidden" id="frmBuscador-filter-params" value="" />                        
                    <input type="text" name="cadena" id="frmBuscadorCadena" value=""  placeholder="Escriba aqui texto" class="form-control">
                </div>
                 <div class="col-md-2"><button class="col-md-12 btn btn-primary" type="submit"><span class="glyphicon glyphicon-search"></span> BUSCAR</button></div>
            </form> 
<br>
<br>
<br>
<br>
<br>
        
          <form action="formularioValidacion2.html" id="miForm1" method="POST">
        <fieldset>
            <legend>Datos Personales</legend>
        <table>
           
        <div class="form-group">
        <label class="control-label col-xs-3">Nombre:</label>
        <div class="col-xs-9">
        <input type="text" class="form-control" id="mi_nombre" placeholder="Nombre">
        </div>

        <br>
        <br>
        <br>

        <div class="form-group">
        <label class="control-label col-xs-3">Password:</label>
        <div class="col-xs-9">
        <input type="password" class="form-control" id="mi_password" placeholder="password">
        </div>
    </div>

    <br>
    <br>
        
        <div class="form-group">
        <label class="control-label col-xs-3">Departamento:</label>
        <div class="col-xs-5">

                    <select class="form-control" id="mi_departamento" name="departamento">
                        <option value=""></option>
                        <option value="1">San salvador</option>
                        <option value="2">Santa Ana</option>
                        <option value="3">Sonsonate</option>
                    </select>                   
                </td>
        </div>
    </div>

<br>
<br>
    <div class="form-group">
    <label class="control-label col-xs-3">Email:</label>
    <div class="col-xs-9">
    <input type="text" class= "form-control" id="mi_email" name="mail" placeholder="Email">
    </div>
    </div>

    <br>
    <br>
    <br>
    <div class="form-group">
    <label class="control-label col-xs-3">Edad:</label>
    <div class="col-xs-9">
    <input type="text" class= "form-control" id="mi_edad" name="edad" placeholder="Edad">
    </div>
    </div>
<br>
<br>

<div class="form-group">
        <div class="col-xs-offset-3 col-xs-9">
             <button type="submit" value="Enviar" id="boton" name="enviar" class="btn btn-primary">Acepto crear mi cuenta y continuar</button>

            <input type="reset" class="btn btn-primary" value="Limpiar">
        </div>
    </div>

   
               
        </table>
        </fieldset> 
    </form>



 
        </script>
</body>

</html>

